project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left: 
      - text: Hands-on Exercises
        menu: 
          - text: Hands-on Exercise 1.1
            href: hands-on_exercises/hands-on_ex1/hands-on_ex1.1.qmd
          - text: Hands-on Exercise 1.2
            href: hands-on_exercises/hands-on_ex1/hands-on_ex1.2.qmd
          - text: Hands-on Exercise 2
            href: hands-on_exercises/hands-on_ex2/hands-on_ex2.qmd
          - text: Hands-on Exercise 3
            href: hands-on_exercises/hands-on_ex3/hands-on_ex3.qmd
          - text: Hands-on Exercise 4
            href: hands-on_exercises/hands-on_ex4/hands-on_ex4.qmd
          - text: Hands-on Exercise 5
            href: hands-on_exercises/hands-on_ex4/hands-on_ex5.qmd  
      - text: In-class Exercises
        menu: 
          - text: In-class Exercise 1
            href: in-class_exercises/in-class_ex1/in-class_ex1.qmd
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

