<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>ISSS624 - Assignment 1</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">ISSS624</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hands-on-exercises" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Hands-on Exercises</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-hands-on-exercises">    
        <li>
    <a class="dropdown-item" href="../../hands-on_exercises/hands-on_ex1/hands-on_ex1.1.html">
 <span class="dropdown-text">Hands-on Exercise 1.1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../hands-on_exercises/hands-on_ex1/hands-on_ex1.2.html">
 <span class="dropdown-text">Hands-on Exercise 1.2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../hands-on_exercises/hands-on_ex2/hands-on_ex2.html">
 <span class="dropdown-text">Hands-on Exercise 2</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-in-class-exercises" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">In-class Exercises</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-in-class-exercises">    
        <li>
    <a class="dropdown-item" href="../../in-class_exercises/in-class_ex1/in-class_ex1.html">
 <span class="dropdown-text">In-class Exercise 1</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-assignments" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Assignments</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-assignments">    
        <li>
    <a class="dropdown-item" href="../../assignments/assignment_ex1/assignment_ex1.html">
 <span class="dropdown-text">Assignment 1</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html">
 <span class="menu-text">About</span></a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#birds-of-a-feather-flock-together-do-functionally-similar-water-points-co-occur-in-nigeria" id="toc-birds-of-a-feather-flock-together-do-functionally-similar-water-points-co-occur-in-nigeria" class="nav-link active" data-scroll-target="#birds-of-a-feather-flock-together-do-functionally-similar-water-points-co-occur-in-nigeria">Birds of a feather flock together: Do functionally similar water points co-occur in Nigeria?</a></li>
  <li><a href="#getting-started" id="toc-getting-started" class="nav-link" data-scroll-target="#getting-started">Getting Started</a></li>
  <li><a href="#importing-data" id="toc-importing-data" class="nav-link" data-scroll-target="#importing-data">Importing Data</a>
  <ul class="collapse">
  <li><a href="#importing-water-point-geospatial-data" id="toc-importing-water-point-geospatial-data" class="nav-link" data-scroll-target="#importing-water-point-geospatial-data">Importing Water Point Geospatial Data</a></li>
  <li><a href="#importing-nigeria-lga-boundary-data" id="toc-importing-nigeria-lga-boundary-data" class="nav-link" data-scroll-target="#importing-nigeria-lga-boundary-data">Importing Nigeria LGA Boundary Data</a></li>
  </ul></li>
  <li><a href="#data-preparation" id="toc-data-preparation" class="nav-link" data-scroll-target="#data-preparation">Data Preparation</a>
  <ul class="collapse">
  <li><a href="#recoding-na-values-into-strings" id="toc-recoding-na-values-into-strings" class="nav-link" data-scroll-target="#recoding-na-values-into-strings">Recoding NA values into strings</a></li>
  <li><a href="#extracting-water-point-data" id="toc-extracting-water-point-data" class="nav-link" data-scroll-target="#extracting-water-point-data">Extracting Water Point Data</a></li>
  <li><a href="#performing-point-in-polygon-count" id="toc-performing-point-in-polygon-count" class="nav-link" data-scroll-target="#performing-point-in-polygon-count">Performing Point-in-Polygon Count</a></li>
  <li><a href="#saving-the-analytical-data-table" id="toc-saving-the-analytical-data-table" class="nav-link" data-scroll-target="#saving-the-analytical-data-table">Saving the Analytical Data Table</a></li>
  </ul></li>
  <li><a href="#visualising-the-spatial-distribution-of-water-points" id="toc-visualising-the-spatial-distribution-of-water-points" class="nav-link" data-scroll-target="#visualising-the-spatial-distribution-of-water-points">Visualising the spatial distribution of water points</a></li>
  <li><a href="#creating-spatial-neighbours" id="toc-creating-spatial-neighbours" class="nav-link" data-scroll-target="#creating-spatial-neighbours">Creating Spatial Neighbours</a>
  <ul class="collapse">
  <li><a href="#creating-spatial-neighbours-using-contiguity-method-queen" id="toc-creating-spatial-neighbours-using-contiguity-method-queen" class="nav-link" data-scroll-target="#creating-spatial-neighbours-using-contiguity-method-queen">Creating Spatial Neighbours using Contiguity Method (Queen)</a></li>
  <li><a href="#creating-spatial-neighbours-using-distance-based-method" id="toc-creating-spatial-neighbours-using-distance-based-method" class="nav-link" data-scroll-target="#creating-spatial-neighbours-using-distance-based-method">Creating Spatial Neighbours using Distance-Based Method</a>
  <ul class="collapse">
  <li><a href="#transformation-to-projected-coordinate-system" id="toc-transformation-to-projected-coordinate-system" class="nav-link" data-scroll-target="#transformation-to-projected-coordinate-system">Transformation to Projected Coordinate System</a></li>
  <li><a href="#computing-centroids-of-each-aerial-unit-polygon" id="toc-computing-centroids-of-each-aerial-unit-polygon" class="nav-link" data-scroll-target="#computing-centroids-of-each-aerial-unit-polygon">Computing Centroids of Each Aerial Unit Polygon</a></li>
  <li><a href="#creating-spatial-neighbours-using-fixed-distance-method" id="toc-creating-spatial-neighbours-using-fixed-distance-method" class="nav-link" data-scroll-target="#creating-spatial-neighbours-using-fixed-distance-method">Creating Spatial Neighbours using Fixed Distance Method</a></li>
  <li><a href="#creating-spatial-neighbours-using-adaptive-distance-method" id="toc-creating-spatial-neighbours-using-adaptive-distance-method" class="nav-link" data-scroll-target="#creating-spatial-neighbours-using-adaptive-distance-method">Creating Spatial Neighbours using Adaptive Distance Method</a></li>
  </ul></li>
  <li><a href="#visualising-neighbours" id="toc-visualising-neighbours" class="nav-link" data-scroll-target="#visualising-neighbours">Visualising Neighbours</a>
  <ul class="collapse">
  <li><a href="#neighbours-from-queen-contiguity-method" id="toc-neighbours-from-queen-contiguity-method" class="nav-link" data-scroll-target="#neighbours-from-queen-contiguity-method">Neighbours from Queen Contiguity Method</a></li>
  <li><a href="#neighbours-from-fixed-distance-method" id="toc-neighbours-from-fixed-distance-method" class="nav-link" data-scroll-target="#neighbours-from-fixed-distance-method">Neighbours from Fixed Distance Method</a></li>
  <li><a href="#neighbours-from-adaptive-distance-method" id="toc-neighbours-from-adaptive-distance-method" class="nav-link" data-scroll-target="#neighbours-from-adaptive-distance-method">Neighbours from Adaptive Distance Method</a></li>
  </ul></li>
  <li><a href="#determining-the-spatial-neighbours-to-use" id="toc-determining-the-spatial-neighbours-to-use" class="nav-link" data-scroll-target="#determining-the-spatial-neighbours-to-use">Determining the Spatial Neighbours to use</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Assignment 1</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="birds-of-a-feather-flock-together-do-functionally-similar-water-points-co-occur-in-nigeria" class="level1">
<h1>Birds of a feather flock together: Do functionally similar water points co-occur in Nigeria?</h1>
<p>Water is an important resource to mankind. Yet over 40% of the global population does not have access to sufficient clean water. Developing countries especially are most affected by water shortages and poor water quality.</p>
<p>The purpose of this project is to apply appropriate global and local measures of spatial association techniques to reveal the spatial patterns of Non Functional water points in Nigeria.</p>
<p>More background on the study and the data sources can be found <a href="https://isss624-ay2022-23nov.netlify.app/take-home_ex01">here</a>.</p>
</section>
<section id="getting-started" class="level1">
<h1>Getting Started</h1>
<p>Install and load the required packages.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(tidyverse, sf, spdep, tmap, funModeling)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="importing-data" class="level1">
<h1>Importing Data</h1>
<p>There are two geospatial datsets that will be used, they are:</p>
<ul>
<li><p><code>geo_export</code>: water point geospatial data in rural areas from Water Point Data Exchange (WPdx)</p></li>
<li><p><code>nga_admbnda_adm2_osgof_20190417</code>: nigeria Level-2 admin boundary polygon GIS data</p></li>
</ul>
<section id="importing-water-point-geospatial-data" class="level2">
<h2 class="anchored" data-anchor-id="importing-water-point-geospatial-data">Importing Water Point Geospatial Data</h2>
<p>We will read in the <code>geo_export</code> data and extract out only the rows relating to Nigeria, which is the country of interest for our study.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>wp <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="at">dsn =</span> <span class="st">"data"</span>,</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">layer =</span> <span class="st">"geo_export"</span>,</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">crs =</span> <span class="dv">4326</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(clean_coun <span class="sc">==</span> <span class="st">"Nigeria"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Next, we save the extracted sf data table (i.e., wp) into an output file in rds data format. For subsequent analysis, we can just load this extracted file.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(wp, <span class="st">"data/wp_nga.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="importing-nigeria-lga-boundary-data" class="level2">
<h2 class="anchored" data-anchor-id="importing-nigeria-lga-boundary-data">Importing Nigeria LGA Boundary Data</h2>
<p>Next, we will import the LGA boundary data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>nga <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="at">dsn =</span> <span class="st">"data"</span>,</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>               <span class="at">layer =</span> <span class="st">"nga_admbnda_adm2_osgof_20190417"</span>,</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">crs =</span> <span class="dv">4326</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="data-preparation" class="level1">
<h1>Data Preparation</h1>
<section id="recoding-na-values-into-strings" class="level2">
<h2 class="anchored" data-anchor-id="recoding-na-values-into-strings">Recoding NA values into strings</h2>
<p>In the code chunk below, <em>replace_na()</em> is used to recode all NA values in <code>status_cle</code> field into Unknown.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>wp_nga <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data/wp_nga.rds"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">status_cle =</span> <span class="fu">replace_na</span>(status_cle, <span class="st">"Unknown"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="extracting-water-point-data" class="level2">
<h2 class="anchored" data-anchor-id="extracting-water-point-data">Extracting Water Point Data</h2>
<p>We want to examine the different classes of <code>status_cle</code> in our water point data. To get a quick view of the distribution, we use <em>freq()</em> from funModeling package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">freq</span>(<span class="at">data =</span> wp_nga, <span class="at">input =</span> <span class="st">"status_cle"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Then, we will extract the water point data into three different dataframes based on functional, non-functional and unknown class.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>wp_functional <span class="ot">&lt;-</span> wp_nga <span class="sc">%&gt;%</span> </span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(status_cle <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Functional"</span>,</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>                           <span class="st">"Functional but needs repair"</span>,</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>                           <span class="st">"Functional but not in use"</span>))</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>wp_nonfunctional <span class="ot">&lt;-</span> wp_nga <span class="sc">%&gt;%</span> </span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(status_cle <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Non-Functional"</span>,</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>                           <span class="st">"Non-Functional due to dry season"</span>,</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>                           <span class="st">"Abandoned/Decommissioned"</span>,</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>                           <span class="st">"Abandoned"</span>,</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>                           <span class="st">"Non functional due to dry season"</span>))</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>wp_unknown <span class="ot">&lt;-</span> wp_nga <span class="sc">%&gt;%</span> </span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(status_cle <span class="sc">==</span> <span class="st">"Unknown"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="performing-point-in-polygon-count" class="level2">
<h2 class="anchored" data-anchor-id="performing-point-in-polygon-count">Performing Point-in-Polygon Count</h2>
<p>We want to find out how many water points from each class are there in each admin boundary in Nigeria. Using <em>st_intersects()</em>, it will return a list of the indexes of water points found in each admin boundary, then we use <em>lengths()</em> to obtain the number of water points and add the value to the newly created columns.</p>
<p>(<em>Note that st_intersects(points, polygon) will return TRUE/FALSE on each of the points, whereas st_intersects(polygon_points) will return the indexes of the points that fall inside each polygon. We should also not confuse with st_intersection(x, y), which is another function that returns the a geometry object that has the same class as the first argument (x), e.g., it can be used to return a polygon geometry of the intersection between two polygons.)</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>nga_wp <span class="ot">&lt;-</span> nga <span class="sc">%&gt;%</span> </span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">total_wp =</span> <span class="fu">lengths</span>(<span class="fu">st_intersects</span>(nga, wp_nga))) <span class="sc">%&gt;%</span> </span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">total_wp_functional =</span> <span class="fu">lengths</span>(<span class="fu">st_intersects</span>(nga, wp_functional))) <span class="sc">%&gt;%</span> </span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">total_wp_nonfunctional =</span> <span class="fu">lengths</span>(<span class="fu">st_intersects</span>(nga, wp_nonfunctional))) <span class="sc">%&gt;%</span> </span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">total_wp_unknown =</span> <span class="fu">lengths</span>(<span class="fu">st_intersects</span>(nga, wp_unknown)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="saving-the-analytical-data-table" class="level2">
<h2 class="anchored" data-anchor-id="saving-the-analytical-data-table">Saving the Analytical Data Table</h2>
<p>We further wrangle the data table to derive two fields namely pct_functional and pct_nonfunctional. To keep the file size small, we select relevant fields from the data table and save them separately. For subsequently analysis, we will only need to use this extracted dataset (i.e., <code>nga_wp.rds</code> and can remove all other raw datasets.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>nga_wp <span class="ot">&lt;-</span> nga_wp <span class="sc">%&gt;%</span> </span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pct_functional =</span> total_wp_functional<span class="sc">/</span>total_wp) <span class="sc">%&gt;%</span> </span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pct_nonfunctional =</span> total_wp_nonfunctional<span class="sc">/</span>total_wp) <span class="sc">%&gt;%</span> </span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(ADM2_EN, ADM2_PCODE, ADM1_PCODE, ADM0_EN, total_wp, total_wp_functional,</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>         total_wp_nonfunctional, total_wp_unknown, pct_functional,</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>         pct_nonfunctional)</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(nga_wp, <span class="st">"data/nga_wp.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="visualising-the-spatial-distribution-of-water-points" class="level1">
<h1>Visualising the spatial distribution of water points</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>nga_wp <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data/nga_wp.rds"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="st">"wp_func"</span> <span class="ot">=</span> <span class="st">"total_wp_functional"</span>,</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>         <span class="st">"wp_nonfunc"</span> <span class="ot">=</span> <span class="st">"total_wp_nonfunctional"</span>,</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>         <span class="st">"wp_unknown"</span> <span class="ot">=</span> <span class="st">"total_wp_unknown"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(nga_wp) <span class="sc">+</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(<span class="at">col =</span> <span class="fu">c</span>(<span class="st">"total_wp"</span>, <span class="st">"wp_func"</span>, <span class="st">"wp_nonfunc"</span>, <span class="st">"wp_unknown"</span>)) <span class="sc">+</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">legend.position =</span> <span class="fu">c</span>(<span class="st">"right"</span>, <span class="st">"bottom"</span>),</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title =</span> <span class="st">"Spatial Distribution of Water Points in Nigeria"</span>,</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.position =</span> <span class="st">"center"</span>,</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.size =</span> <span class="dv">1</span>,</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">asp =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="assignment_ex1_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="creating-spatial-neighbours" class="level1">
<h1>Creating Spatial Neighbours</h1>
<p>Creating spatial weights is a necessary step in using areal data, to check whether this is spatial patterning. The first step is to define which relationships between observations are to be assigned as neighbours (i.e., the neighbour criterion to be used).</p>
<p>There are two general methods for defining spatial neighbours:</p>
<ol type="1">
<li><strong>Contiguity Method (aka Adjacency Method)</strong> - Effective when polygons are similar in size and distribution, and when spatial relationships are a function of polygon proximity (the idea that if two polygons share a boundary, spatial interaction between them increases). Variations include using <strong>Queen’s</strong> or <strong>Rook’s</strong> case.</li>
<li><strong>Distance-Based Method</strong> - Effective for point data, or when there is large variation in polygon size. Variations include using <strong>Fixed Distance</strong> or <strong>Adaptive Distance</strong>.</li>
</ol>
<p>Note that in the <strong>spdep</strong> package, neighbour relationships between n observations are presented by an object class <strong>nb</strong>. It is a list of length n with the index numbers of neighbours of each component recorded as an integer vector. If any observations has no neighbours, the component contains an integer zero.</p>
<section id="creating-spatial-neighbours-using-contiguity-method-queen" class="level2">
<h2 class="anchored" data-anchor-id="creating-spatial-neighbours-using-contiguity-method-queen">Creating Spatial Neighbours using Contiguity Method (Queen)</h2>
<p>We will first explore the use of contiguity method for defining of neighbours. For this study, we will use the Queen’s case for defining the shared boundaries (refer figure below).</p>
<p><img src="images/paste-DFE2557D.png" class="img-fluid" width="446"></p>
<p>We will use the function <a href="https://r-spatial.github.io/spdep/reference/poly2nb.html"><em>poly2nb()</em></a> of <strong>spdep</strong> package to build the neighbours list nb object based on Queen contiguity method.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>nb_queen <span class="ot">&lt;-</span> <span class="fu">poly2nb</span>(nga_wp, <span class="at">queen=</span><span class="cn">TRUE</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(nb_queen)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Neighbour list object:
Number of regions: 774 
Number of nonzero links: 4440 
Percentage nonzero weights: 0.7411414 
Average number of links: 5.736434 
1 region with no links:
86
Link number distribution:

  0   1   2   3   4   5   6   7   8   9  10  11  12  14 
  1   2  14  57 125 182 140 122  72  41  12   4   1   1 
2 least connected regions:
138 560 with 1 link
1 most connected region:
508 with 14 links</code></pre>
</div>
</div>
<p>The summary report above shows that there are 774 areal units in Nigeria. Using the Queen contiguity method, the areal units have a range of neighbours between 0 and 14, with an average of 5.7 neighbours and most areal units having between 4 and 7 neighbours. Notably, one areal unit [86] has no links (likely an isolated region that does not share boundary with the other regions). This might be an issue for subsequent analysis.</p>
<p>We can find out more about this areal unit [86] based on its index using the code chunk below. From the results, we know that this region is named Bakassi. It is however not visible on the map.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract region without neighbour</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>reg_without_neighbour <span class="ot">&lt;-</span> nga_wp[<span class="dv">86</span>,]</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(reg_without_neighbour<span class="sc">$</span>ADM2_EN)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Bakassi"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the region in map</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qtm</span>(nga_wp) <span class="sc">+</span> <span class="fu">qtm</span>(reg_without_neighbour, <span class="at">fill =</span> <span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="assignment_ex1_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Similarly, we can examine the areal unit [508] with the most neighbours. This region is named Mokwa and while it is not the biggest area geographically, its long shape likely contributed to it sharing boundaries with many other regions.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract region with max neighbours (14)</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>reg_max_neighbour <span class="ot">&lt;-</span> nga_wp[<span class="dv">508</span>,]</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(reg_max_neighbour<span class="sc">$</span>ADM2_EN)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Mokwa"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the region in map</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qtm</span>(nga_wp) <span class="sc">+</span> <span class="fu">qtm</span>(reg_max_neighbour, <span class="at">fill =</span> <span class="st">"green"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="assignment_ex1_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="creating-spatial-neighbours-using-distance-based-method" class="level2">
<h2 class="anchored" data-anchor-id="creating-spatial-neighbours-using-distance-based-method">Creating Spatial Neighbours using Distance-Based Method</h2>
<p>Next we will explore the use of distance-based methods for defining of neighbours. The first step of computing distance-based neighbours is to calculate the <strong>centroid coordinates</strong> of each aerial unit polygon. It is useful for us to transform the original data from geographic coordinate system to <strong>projected coordinate system</strong>. This is because geographic coordinate system is not appropriate if the analysis need to use distance or/and area measurements.</p>
<p>Thereafter, there are two different approaches of the distance-based method:</p>
<ol type="1">
<li><strong>Fixed Distance</strong> - Some areas like the rural areas might be more sparse than the urban areas, resulting in them having more neighbours based on the fixed distance method, leading to potential large estimate variances. We will need to ensure that all features should have at least one neighbour.</li>
<li><strong>Adaptive Distance</strong> - Chooses the k nearest points as neighbour and hence ensures that each areal unit has a minimum number of neighbours for analysis. Effective when the values associated with our features are skewed (hence each features should be evaluated with a minimum number of neighbours) or when the distribution of our data varies across the study area such that some regions are further away from others.</li>
</ol>
<section id="transformation-to-projected-coordinate-system" class="level3">
<h3 class="anchored" data-anchor-id="transformation-to-projected-coordinate-system">Transformation to Projected Coordinate System</h3>
<p>First, we check the coordinate reference system of our data. The crs is currently in EPSG: 4326.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_crs</span>(nga_wp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Coordinate Reference System:
  User input: EPSG:4326 
  wkt:
GEOGCRS["WGS 84",
    DATUM["World Geodetic System 1984",
        ELLIPSOID["WGS 84",6378137,298.257223563,
            LENGTHUNIT["metre",1]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["geodetic latitude (Lat)",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["geodetic longitude (Lon)",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    USAGE[
        SCOPE["Horizontal component of 3D system."],
        AREA["World."],
        BBOX[-90,-180,90,180]],
    ID["EPSG",4326]]</code></pre>
</div>
</div>
<p>We will convert to Projected Coordinate Systems of Nigeria for the subsequent steps in our distance-based method. There are three Projected Coordinate Systems of Nigeria, they are: EPSG: 26391, 26392, and 26303. For this study, we will use EPSG: 26391.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>nga_wp_projected <span class="ot">&lt;-</span> <span class="fu">st_transform</span>(nga_wp, <span class="at">crs=</span><span class="dv">26391</span>)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">st_crs</span>(nga_wp_projected)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Coordinate Reference System:
  User input: EPSG:26391 
  wkt:
PROJCRS["Minna / Nigeria West Belt",
    BASEGEOGCRS["Minna",
        DATUM["Minna",
            ELLIPSOID["Clarke 1880 (RGS)",6378249.145,293.465,
                LENGTHUNIT["metre",1]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4263]],
    CONVERSION["Nigeria West Belt",
        METHOD["Transverse Mercator",
            ID["EPSG",9807]],
        PARAMETER["Latitude of natural origin",4,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",4.5,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",0.99975,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",230738.26,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["(E)",east,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["(N)",north,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    USAGE[
        SCOPE["Engineering survey, topographic mapping."],
        AREA["Nigeria - onshore west of 6°30'E, onshore and offshore shelf."],
        BBOX[3.57,2.69,13.9,6.5]],
    ID["EPSG",26391]]</code></pre>
</div>
</div>
</section>
<section id="computing-centroids-of-each-aerial-unit-polygon" class="level3">
<h3 class="anchored" data-anchor-id="computing-centroids-of-each-aerial-unit-polygon">Computing Centroids of Each Aerial Unit Polygon</h3>
<p>To compute the centroid of each areal unit polygon, we use <a href="https://purrr.tidyverse.org/reference/map.html"><em>map_dbl()</em></a> from purrr package and <a href="https://r-spatial.github.io/sf/reference/geos_unary.html"><em>st_centroid()</em></a> from sf package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>longitude <span class="ot">&lt;-</span> <span class="fu">map_dbl</span>(nga_wp_projected<span class="sc">$</span>geometry, <span class="sc">~</span><span class="fu">st_centroid</span>(.x)[[<span class="dv">1</span>]])</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>latitude <span class="ot">&lt;-</span> <span class="fu">map_dbl</span>(nga_wp_projected<span class="sc">$</span>geometry, <span class="sc">~</span><span class="fu">st_centroid</span>(.x)[[<span class="dv">2</span>]])</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>coords <span class="ot">&lt;-</span> <span class="fu">cbind</span>(longitude, latitude)</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(coords)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     longitude  latitude
[1,]  549364.0  123694.9
[2,]  547123.4  120376.5
[3,] 1189496.9 1059770.9
[4,]  489057.4  534262.6
[5,]  593718.2  113824.1
[6,]  642618.7  251222.3</code></pre>
</div>
</div>
</section>
<section id="creating-spatial-neighbours-using-fixed-distance-method" class="level3">
<h3 class="anchored" data-anchor-id="creating-spatial-neighbours-using-fixed-distance-method">Creating Spatial Neighbours using Fixed Distance Method</h3>
<p>With the centroids computed, we can now create spatial neighbours using the distance-based method. First, we will explore the fixed distance method.</p>
<p>The following functions will be used:</p>
<ul>
<li><p><a href="https://r-spatial.github.io/spdep/reference/knearneigh.html"><em>knearneigh()</em></a> of <strong>spdep</strong> which returns a matrix with the indices of points belonging to the set of the k nearest neighbours of each other</p></li>
<li><p><a href="https://r-spatial.github.io/spdep/reference/knn2nb.html"><em>knn2nb()</em></a> which converts the knn object returned by <em>knearneigh()</em> into a neighbours list of class nb with a list of integer vectors containing neighbour region number ids</p></li>
<li><p><a href="https://r-spatial.github.io/spdep/reference/nbdists.html"><em>nbdists()</em></a> of <strong>spdep</strong> to calculate a list of vectors of distances corresponding to the neighbour object. The function returns in the units of the coordinates if the coordinates are projected, in km otherwise</p></li>
<li><p><a href="https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/unlist"><em>unlist()</em></a> for removal of the list structure of the returned object.</p></li>
<li><p><a href="https://r-spatial.github.io/spdep/reference/dnearneigh.html"><em>dnearneigh()</em></a> of <strong>spdep</strong> package to find an neighbours based on an interpoint distance</p></li>
</ul>
<p>To ensure that each region is linked to at least one neighbour, we will calculate a list of vectors of distances corresponding to the first neighbour object (i.e., k=1). Then using the maximum value value in the list of distances as our upper threshold gives certainty that all units will have at least one neighbour (as compared to setting an arbitrary distance value as upper threshold).</p>
<p>The summary report below shows that the largest first nearest neighbour distance is 72139m, so we will use this as our upper threshold distance.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>nb_dist_k1 <span class="ot">&lt;-</span> <span class="fu">knn2nb</span>(<span class="fu">knearneigh</span>(coords, <span class="at">k=</span><span class="dv">1</span>))</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>k1dists <span class="ot">&lt;-</span> <span class="fu">unlist</span>(<span class="fu">nbdists</span>(nb_dist_k1, coords))</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(k1dists)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   2669   12834   20304   22084   27783   72139 </code></pre>
</div>
</div>
<p>The following code chunk computes the fixed distance neighbours.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>nb_dist_fixed <span class="ot">&lt;-</span> <span class="fu">dnearneigh</span>(coords, <span class="dv">0</span>, <span class="dv">72139</span>)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(nb_dist_fixed)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Neighbour list object:
Number of regions: 774 
Number of nonzero links: 18130 
Percentage nonzero weights: 3.026327 
Average number of links: 23.42377 
Link number distribution:

 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 
 5  9 11 22 32 35 33 34 29 35 27 18 21 23 16 12 12 11 16 17 16 10 14 10  5 13 
27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 
12  5 15 13 12  7 10  8 12  5 12 17 14  9 10  4  5  3  7  6 11  8  5  5  4  2 
53 54 55 56 57 58 59 60 61 62 63 64 65 67 68 70 
 3  3  6  3  5  6  2  5  5  8  6  6  4  3  1  1 
5 least connected regions:
90 112 123 237 670 with 1 link
1 most connected region:
585 with 70 links</code></pre>
</div>
</div>
<p>The summary report above shows that there are 774 areal units in Nigeria. Using the fixed distance method, the areal units have a range of neighbours between 1 and 70. This is a big variation of the number of neighbours.</p>
</section>
<section id="creating-spatial-neighbours-using-adaptive-distance-method" class="level3">
<h3 class="anchored" data-anchor-id="creating-spatial-neighbours-using-adaptive-distance-method">Creating Spatial Neighbours using Adaptive Distance Method</h3>
<p>Based on the contiguity method used in the previous section, the areal units have an average of 5.7 neighbours, with the majority between the range of 4 and 7 neighbours. Using this as a reference, we will use <strong>k=6</strong> for our adaptive distance method, i.e., choosing the 6 nearest points as neighbours. Using the adaptive distance method, all regions will have 6 neighbours.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>nb_dist_k6 <span class="ot">&lt;-</span> <span class="fu">knn2nb</span>(<span class="fu">knearneigh</span>(coords, <span class="at">k=</span><span class="dv">6</span>))</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>nb_dist_k6</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Neighbour list object:
Number of regions: 774 
Number of nonzero links: 4644 
Percentage nonzero weights: 0.7751938 
Average number of links: 6 
Non-symmetric neighbours list</code></pre>
</div>
</div>
</section>
</section>
<section id="visualising-neighbours" class="level2">
<h2 class="anchored" data-anchor-id="visualising-neighbours">Visualising Neighbours</h2>
<p>We can do a visualisation of the neighbours based on Queen contiguity method, fixed distance method and adaptive distance method. However, as the regions are too numerous, the visualisations have limited utility in this study.</p>
<section id="neighbours-from-queen-contiguity-method" class="level3">
<h3 class="anchored" data-anchor-id="neighbours-from-queen-contiguity-method">Neighbours from Queen Contiguity Method</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(nga_wp_projected<span class="sc">$</span>geometry, <span class="at">border=</span><span class="st">"lightgrey"</span>)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(nb_queen, coords, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">cex =</span> <span class="fl">0.6</span>, <span class="at">add =</span> <span class="cn">TRUE</span>, <span class="at">col=</span> <span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="assignment_ex1_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="neighbours-from-fixed-distance-method" class="level3">
<h3 class="anchored" data-anchor-id="neighbours-from-fixed-distance-method">Neighbours from Fixed Distance Method</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(nga_wp_projected<span class="sc">$</span>geometry, <span class="at">border=</span><span class="st">"lightgrey"</span>)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(nb_dist_fixed, coords, <span class="at">add=</span><span class="cn">TRUE</span>)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(nb_dist_k1, coords, <span class="at">add=</span><span class="cn">TRUE</span>, <span class="at">col=</span><span class="st">"red"</span>, <span class="at">length=</span><span class="fl">0.08</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="assignment_ex1_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="neighbours-from-adaptive-distance-method" class="level3">
<h3 class="anchored" data-anchor-id="neighbours-from-adaptive-distance-method">Neighbours from Adaptive Distance Method</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(nga_wp_projected<span class="sc">$</span>geometry, <span class="at">border=</span><span class="st">"lightgrey"</span>)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(nb_dist_k6, coords, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">cex =</span> <span class="fl">0.6</span>, <span class="at">add =</span> <span class="cn">TRUE</span>, <span class="at">col =</span> <span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="assignment_ex1_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="determining-the-spatial-neighbours-to-use" class="level2">
<h2 class="anchored" data-anchor-id="determining-the-spatial-neighbours-to-use">Determining the Spatial Neighbours to use</h2>
<p>To recap, we have explored three ways to build the spatial neighbours, specifically the Queen contiguity method, fixed distance method and adaptive distance method.</p>
<p>The Queen contiguity method resulted in one region (Bakassi) having no links at all and is hence not suitable for this geographical study.</p>
<p>The fixed distance method resulted in regions having a very large range of the number of neighbours (between 1 and 70). This is indicative that the regions could have a large variation in sizes (hence distance from centroid) and large variation in density. This might not be a suitable method for this geographical study.</p>
<p>We will choose the <strong>adaptive distance method</strong> (with k=6) for the purpose of this study as it is the most reasonable based on the geographical distribution of this study. All regions will have 6 neighbours for our evaulation and analysis.</p>
<p><strong>Subsequent steps:</strong></p>
<ol type="1">
<li>Spatial Neighbours
<ol type="1">
<li><p>Define which are neighbours (choosing the neighbour criterion)</p>
<ul>
<li><p>Continuity Spatial Weights Method</p>
<ul>
<li><p>QUEEN method using <em>poly2nb(sf, queen=TRUE)</em></p></li>
<li><p>ROOK method using <em>poly2nb(sf, queen=FALSE)</em></p></li>
<li></li>
</ul></li>
<li><p>Distance-based Method</p>
<ul>
<li>Compute the centroid coordinates of the areas using:
<ul>
<li><p><em>longitude &lt;- map_dbl(sf$geometry, ~st_centroid(.x)[[1]])</em></p></li>
<li><p><em>latitude &lt;- map_dbl(sf$geometry, ~st_centroid(.x)[[2]])</em></p></li>
<li><p><em>coords &lt;- cbind(longitude, latitude)</em></p></li>
</ul></li>
<li>Fixed distance weight matrix using <em>dnearneigh(coords, lower, upper, longlat=TRUE)</em>. The fixed distance weight matrix defines all areas with centroids within defined lower-upper distance threshold as areas. To get the upper threshold, we first do <em>k1 &lt;- knn2nb(knearneigh(coords))</em> to convert the knn neighbours into a nb class object, then take <em>nbdists(k1, coords)</em> to find the distances. We can take the max distance here as a reference for the upper threshold so as to confirm all unit will have a least one neighbour</li>
<li>Adaptive distance weight matrix enforces a fixed number of neighbours e.g., using <em>knn2nb(knearneigh(coords, k=6))</em></li>
</ul></li>
</ul></li>
<li><p>Assign weights to the identified neighbour links (spatial weights)</p>
<ul>
<li><p>Row-standardised weight matrix based on queen’s method using <em>nb2listw(nb_object, style=“W”, zero.policy=TRUE)</em></p></li>
<li><p>Weight matrix based on inverse distance method using computation of inverse distance (<em>dist &lt;- nbdists(wm_q, coords, longlat = TRUE)</em> then <em>ids &lt;- lapply(dist, <strong>function</strong>(x) 1/(x))).</em> After that take <em>rswm_ids &lt;- nb2listw(wm_q, glist=ids, style=“B”, zero.policy=TRUE)</em></p></li>
<li><p>Raw weight matrix using <em>b_weights &lt;- lapply(wm_q1, <strong>function</strong>(x) 0*x + 1)</em> then <em>b_weights2 &lt;- nb2listw(wm_q1, glist = b_weights, style = “B”)</em></p></li>
</ul></li>
<li><p>Application of Spatial Weight Matrix (using <em>lag.listw()</em>)</p>
<ul>
<li><p>Spatial Lag with row-standarised weights taking row-standardised weight matrix based on queen’s method as spatial weight</p></li>
<li><p>Spatial Lag as a sum of neighbouring values taking raw weight matrix as spatial weight</p></li>
<li><p>Spatial window average (first include.self() then take repeat steps to compute row-standardised weight matrix based on queen’s method and take that as spatial weight)</p></li>
<li><p>Spatial window sum (first include.self() then take repeat steps to compute raw weight matrix and take that as spatial weight)</p></li>
</ul></li>
</ol></li>
<li>Check Global Spatial Autocorrelation, i.e.&nbsp;whether spatial distribution is random or are neighbours similar to each other
<ol type="1">
<li><p>Moran’s I - using the decided spatial weights computed in the previous section, do a moran test (moran.test(sf$variable, listw=spatial_weight,))</p></li>
<li><p>Monte Carlo Moran’s I - moran.mc()</p></li>
<li><p>Geary’s C using the decided spatial weights computed in the previous section, do a geary test (geary.test(sf$variable, listw=spatial_weight,))</p></li>
<li><p>Monte Carlo Geary’s C - geary.mc()</p></li>
</ol></li>
<li>Do a Spatial Correlogram to examine patterns of global spatial autocorrelation as we increase the distance (lag) using sp.correlogram()</li>
<li>Do Cluster and Outlier Analysis using Local Indicators of Spatial Association
<ol type="1">
<li><p>Compute local moran using localmoran()</p></li>
<li><p>To view the general pattern: we can map the local moran’s I values and p-values on the map</p></li>
<li><p>For a quick view of the relationship between the values of the choen attribute at each location and the average value of the same attribute at neighbouring locations, we can do a quick Moran scatterplot using moran.plot()</p></li>
<li><p>For a more detailed analysis and mapping, we can assign the locations to four quardrants and plot a LISA Cluster Map. The LISA Cluster Map shows the significant locations colour-coded by their belonging in the quardrant.</p>
<ul>
<li><p>Preparing LISA map classes then plotting LISA map</p></li>
<li><p>Plotting LISA Map</p></li>
</ul></li>
</ol></li>
<li>Hot Spot and Cold Spot Area Analysis (besides detecting clusters and outliers, localised spatial statistics can be also used to detect hot spot and/or cold spot areas. It tells us where features with either high (i.e., hot spots) or low values (cold spots) cluster spatially).
<ol type="1">
<li><p>Getis and Ord’s G Statistics</p>
<p>Note difference:</p>
<p>Moran’s I is a measure of the degree to which the value at a target site is similar to values at adjacent sites. Moran’s I is large and positive when the value for a given target (or for all locations in the global case) is similar to adjacent values and negative when the value at a target is dissimilar to adjacent values.</p>
<p>Getis-Ord G* identifies areas where high or low values cluster in space. G* is high where the sum of values within a neighborhood of a given radius or configuration is high relative to the global average and negative where the sum of values within a neighborhood are small relative to the global average and approaches 0 at intermediate values.</p></li>
<li><p>For G statistics, we need to use distance-based matrix (either fixed distance or adaptive distance). Then we compute the G1 statistics using localG()</p></li>
</ol></li>
</ol>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>